### PR TITLE
feat(app homepage) + adding dependencies

### PR DESCRIPTION
**Pull request by Xtremilicious**
- [x] Designed and developed a homepage for Flowie, as a starting point in our app workflow.
- [x] Added dependencies - `styled-components`, `react-router-dom`
- [x] Set up react-router to support dynamic URLs
- [x] Link button on the home page to access dynamic page
`e.g. localhost:3000/user/xtremilicious` is a dynamic URL which can access the userId to fetch some info about the user

ScreenShot_20200713182741

### CODE REVIEW

**Comment by Diaga** [comment]
Looks nice! 
Should we change "Try Now" to an input field with "Enter your username" hint?

**Comment by Xtremilicious** [comment]
> Looks nice!
> Should we change "Try Now" to an input field with "Enter your username" hint?

Added input button

ScreenShot_20200713182741

**Review by Diaga — APPROVED** [review]
We can go with this! 👍

**Review by SiddharthSham — APPROVED** [review]

**Comment by Xtremilicious** [comment]
Merging.

**Pull request merged**
